default: &default
  adapter: mysql2
  encoding: utf8
  database: db_craft_blog
  username: root
  password:
  host: 127.0.0.1
  socket: tmp/mysql.sock
  pool: 5

development:
  <<: *default
  database: db_craft_blog_dev

test:
  <<: *default
  database: db_craft_blog_test
